return {
  'pwntester/octo.nvim',
  cmd = 'Octo',
  opts = {
    mappings_disable_default = true,
    enable_builtin = true,
    use_local_fs = true,
    -- or "fzf-lua" or "snacks" or "default"
    picker = 'telescope',
    picker_config = {
      mappings = {
        open_in_browser = { lhs = '<C-b>', desc = 'open issue/pr in browser' },
        copy_url = { lhs = '<C-y>', desc = 'copy url to system clipboard' },
        checkout_pr = { lhs = '<C-o>', desc = 'checkout pull request' },
      },
    },

    mappings = {
      issue = {},
      runs = {
        expand_step = { lhs = '', desc = 'expand workflow step' },
        open_in_browser = { lhs = '', desc = 'open workflow run in browser' },
        refresh = { lhs = '', desc = 'refresh workflow' },
        rerun = { lhs = '', desc = 'rerun workflow' },
        rerun_failed = { lhs = '', desc = 'rerun failed workflow' },
        cancel = { lhs = '', desc = 'cancel workflow' },
        copy_url = { lhs = '', desc = 'copy url to system clipboard' },
      },
      review_thread = {},
      notification = {},
      repo = {},
      release = {},
      discussion = {
        discussion_options = { lhs = '<CR>', desc = 'show discussion options' },
        open_in_browser = { lhs = '<C-b>', desc = 'open discussion in browser' },
        next_comment = { lhs = ']c', desc = 'go to next comment' },
        prev_comment = { lhs = '[c', desc = 'go to previous comment' },
        add_comment = { lhs = '<localleader>ca', desc = 'add comment' },
        add_reply = { lhs = '<localleader>cr', desc = 'add reply' },
        delete_comment = { lhs = '<localleader>cd', desc = 'delete comment' },
      },
      pull_request = {
        pr_options = { lhs = '<CR>', desc = 'show PR options' },
        checkout_pr = { lhs = '<localleader>po', desc = 'checkout PR' },
        list_changed_files = { lhs = '<localleader>pf', desc = 'list PR changed files' },
        show_pr_diff = { lhs = '<localleader>pd', desc = 'show PR diff' },
        reload = { lhs = '<C-r>', desc = 'reload PR' },
        open_in_browser = { lhs = '<C-b>', desc = 'open PR in browser' },
        copy_url = { lhs = '<C-y>', desc = 'copy url to system clipboard' },
        goto_file = { lhs = 'gf', desc = 'go to file' },
        add_comment = { lhs = '<localleader>ca', desc = 'add comment' },
        add_reply = { lhs = '<localleader>cr', desc = 'add reply' },
        delete_comment = { lhs = '<localleader>cd', desc = 'delete comment' },
        next_comment = { lhs = ']c', desc = 'go to next comment' },
        prev_comment = { lhs = '[c', desc = 'go to previous comment' },
        review_start = { lhs = '<localleader>rs', desc = 'start a review for the current PR' },
        review_resume = { lhs = '<localleader>rr', desc = 'resume a pending review for the current PR' },
      },
      review_diff = {
        submit_review = { lhs = '<localleader>rs', desc = 'submit review' },
        discard_review = { lhs = '<localleader>rd', desc = 'discard review' },
        add_review_comment = { lhs = '<localleader>ca', desc = 'add a new review comment', mode = { 'n', 'x' } },
        add_review_suggestion = { lhs = '<localleader>cs', desc = 'add a new review suggestion', mode = { 'n', 'x' } },
        focus_files = { lhs = '<localleader>e', desc = 'move focus to changed file panel' },
        toggle_files = { lhs = '<localleader>b', desc = 'hide/show changed files panel' },
        next_thread = { lhs = ']t', desc = 'move to next thread' },
        prev_thread = { lhs = '[t', desc = 'move to previous thread' },
        select_next_entry = { lhs = ']q', desc = 'move to next changed file' },
        select_prev_entry = { lhs = '[q', desc = 'move to previous changed file' },
        select_first_entry = { lhs = '[Q', desc = 'move to first changed file' },
        select_last_entry = { lhs = ']Q', desc = 'move to last changed file' },
        select_next_unviewed_entry = { lhs = ']u', desc = 'move to next unviewed changed file' },
        select_prev_unviewed_entry = { lhs = '[u', desc = 'move to previous unviewed changed file' },
        close_review_tab = { lhs = '<C-c>', desc = 'close review tab' },
        toggle_viewed = { lhs = '<localleader>fv', desc = 'toggle viewer viewed state' },
        goto_file = { lhs = 'gf', desc = 'go to file' },
      },
      submit_win = {
        approve_review = { lhs = '<C-a>', desc = 'approve review', mode = { 'n', 'i' } },
        comment_review = { lhs = '<C-m>', desc = 'comment review', mode = { 'n', 'i' } },
        request_changes = { lhs = '<C-r>', desc = 'request changes review', mode = { 'n', 'i' } },
        close_review_tab = { lhs = '<C-c>', desc = 'close review tab', mode = { 'n', 'i' } },
      },
      file_panel = {
        submit_review = { lhs = '<localleader>rs', desc = 'submit review' },
        discard_review = { lhs = '<localleader>rd', desc = 'discard review' },
        next_entry = { lhs = 'j', desc = 'move to next changed file' },
        prev_entry = { lhs = 'k', desc = 'move to previous changed file' },
        select_entry = { lhs = '<cr>', desc = 'show selected changed file diffs' },
        refresh_files = { lhs = 'R', desc = 'refresh changed files panel' },
        focus_files = { lhs = '<localleader>e', desc = 'move focus to changed file panel' },
        toggle_files = { lhs = '<localleader>b', desc = 'hide/show changed files panel' },
        select_next_entry = { lhs = ']q', desc = 'move to next changed file' },
        select_prev_entry = { lhs = '[q', desc = 'move to previous changed file' },
        select_first_entry = { lhs = '[Q', desc = 'move to first changed file' },
        select_last_entry = { lhs = ']Q', desc = 'move to last changed file' },
        select_next_unviewed_entry = { lhs = ']u', desc = 'move to next unviewed changed file' },
        select_prev_unviewed_entry = { lhs = '[u', desc = 'move to previous unviewed changed file' },
        close_review_tab = { lhs = '<C-c>', desc = 'close review tab' },
        toggle_viewed = { lhs = '<localleader>fv', desc = 'toggle viewer viewed state' },
      },
    },
  },
  keys = {
    { '<leader>o', desc = 'Octo' },
    {
      '<leader>op',
      '<CMD>Octo pr list<CR>',
      desc = 'List GitHub PullRequests',
    },
    {
      '<leader>on',
      '<CMD>Octo notification list<CR>',
      desc = 'List GitHub Notifications',
    },
    {
      '<leader>or',
      '<CMD>Octo review browse<CR>',
      desc = 'Browse PR files'
    }
  },
  dependencies = {
    'nvim-lua/plenary.nvim',
    'nvim-telescope/telescope.nvim',
    -- "ibhagwan/fzf-lua",
    -- OR "folke/snacks.nvim",
    'nvim-tree/nvim-web-devicons',
  },
}
